version: '3.9'
services:
  emprestimos:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: emprestimos
    restart: always
    ports:
      - '8081:8080'
      - '5505:5505'
    environment:
      DB_HOST: jdbc:mysql://database:3306/emprestimos?createDatabaseIfNotExist=true
    depends_on:
      - database
  database:
    image: mysql:5.5
    restart: always
    container_name: database
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DB: "emprestimos"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
networks:
  backend:
    name: emprestimospf



