version: '3'
services:
  emprestimospf:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: emprestimospf/api
    restart: always
    ports:
      - '8081:8080'
      - '5505:5505'
    environment:
      DB_HOST: jdbc:mysql://database:3308/emprestimospf?createDatabaseIfNotExist=true
    depends_on:
      - database
  database:
    image: mysql:5.6
    ports:
      - '3308:3306'
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "emprestimos"
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
